// Date: 10/15/2014 11:51:00 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.makersfactory.marinemod.model;

import java.util.Random;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelJellyfish extends ModelBase {
	// fields
	ModelRenderer Head1;
	ModelRenderer Head2;
	ModelRenderer Head3;
	ModelRenderer Tent5;
	ModelRenderer Tent3;
	ModelRenderer Tent7;
	ModelRenderer Tent2;
	ModelRenderer Tent1;
	ModelRenderer Tent8;
	ModelRenderer Tent6;
	ModelRenderer Tent4;
	Random random;
	double speed = 0;

	public ModelJellyfish(int s) {
		random = new Random();
		textureWidth = 64;
		textureHeight = 64;
		if (s > 0) {

			Head1 = new ModelRenderer(this, 16, 14);
			Head1.addBox(-6F, -6F, -6F, 12, 6, 12);
			Head1.setRotationPoint(0F, 0F, 0F);
			Head1.setTextureSize(64, 64);
			Head1.mirror = true;
			setRotation(Head1, 0F, 0F, 0F);
			Head2 = new ModelRenderer(this, 24, 32);
			Head2.addBox(-5F, -8F, -5F, 10, 2, 10);
			Head2.setRotationPoint(0F, 0F, 0F);
			Head2.setTextureSize(64, 64);
			Head2.mirror = true;
			setRotation(Head2, 0F, 0F, 0F);
			Head3 = new ModelRenderer(this, 32, 44);
			Head3.addBox(-4F, -9F, -4F, 8, 1, 8);
			Head3.setRotationPoint(0F, 0F, 0F);
			Head3.setTextureSize(64, 64);
			Head3.mirror = true;
			setRotation(Head3, 0F, 0F, 0F);
			Tent5 = new ModelRenderer(this, 0, 0);
			Tent5.addBox(-0.4666667F, 0F, -0.4666667F, 1, 22, 1);
			Tent5.setRotationPoint(4F, 0F, 0F);
			Tent5.setTextureSize(64, 64);
			Tent5.mirror = true;
			setRotation(Tent5, 0F, 0F, 0F);
			Tent3 = new ModelRenderer(this, 0, 0);
			Tent3.addBox(-0.5F, 0F, -0.5F, 1, 24, 1);
			Tent3.setRotationPoint(0F, 0F, -4F);
			Tent3.setTextureSize(64, 64);
			Tent3.mirror = true;
			setRotation(Tent3, 0F, 0F, 0F);
			Tent7 = new ModelRenderer(this, 0, 0);
			Tent7.addBox(-0.5F, 0F, -0.5F, 1, 17, 1);
			Tent7.setRotationPoint(0F, 0F, 4F);
			Tent7.setTextureSize(64, 64);
			Tent7.mirror = true;
			setRotation(Tent7, 0F, 0F, 0F);
			Tent2 = new ModelRenderer(this, 0, 0);
			Tent2.addBox(-0.5F, 0F, -0.5F, 1, 19, 1);
			Tent2.setRotationPoint(-3F, 0F, -3F);
			Tent2.setTextureSize(64, 64);
			Tent2.mirror = true;
			setRotation(Tent2, 0F, 0F, 0F);
			Tent1 = new ModelRenderer(this, 0, 0);
			Tent1.addBox(-0.5F, 0F, -0.5F, 1, 18, 1);
			Tent1.setRotationPoint(-4F, 0F, 0F);
			Tent1.setTextureSize(64, 64);
			Tent1.mirror = true;
			setRotation(Tent1, 0F, 0F, 0F);
			Tent8 = new ModelRenderer(this, 0, 0);
			Tent8.addBox(-0.5F, 0F, -0.5F, 1, 24, 1);
			Tent8.setRotationPoint(-3F, 0F, 3F);
			Tent8.setTextureSize(64, 64);
			Tent8.mirror = true;
			setRotation(Tent8, 0F, 0F, 0F);
			Tent6 = new ModelRenderer(this, 0, 0);
			Tent6.addBox(-0.5F, 0F, -0.5F, 1, 21, 1);
			Tent6.setRotationPoint(3F, 0F, 3F);
			Tent6.setTextureSize(64, 64);
			Tent6.mirror = true;
			setRotation(Tent6, 0F, 0F, 0F);
			Tent4 = new ModelRenderer(this, 0, 0);
			Tent4.addBox(-0.5F, 0F, -0.5F, 1, 18, 1);
			Tent4.setRotationPoint(3F, 0F, -3F);
			Tent4.setTextureSize(64, 64);
			Tent4.mirror = true;
			setRotation(Tent4, 0F, 0F, 0F);
		}
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		if (this.Head1 != null) {
			super.render(entity, f, f1, f2, f3, f4, f5);
			setRotationAngles(f, f1, f2, f3, f4, f5, entity);
			Head1.render(f5);
			Head2.render(f5);
			Head3.render(f5);
			Tent5.render(f5);
			Tent3.render(f5);
			Tent7.render(f5);
			Tent2.render(f5);
			Tent1.render(f5);
			Tent8.render(f5);
			Tent6.render(f5);
			Tent4.render(f5);
		}
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
		float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		float r = (float) ((Math.PI * 5.0F) / 180.0F);
		float dir = e.rotationYaw;
		double drag = 1.2D;
		double decay = 0.008D;
		double speedNew = Math.sqrt((e.posX - e.prevPosX) + (e.posZ - e.prevPosZ));
		if (speedNew > speed) speed *= 1.2D;
		else speed -= decay;
		if (speed < 0) speed = 0;
		boolean v = e.velocityChanged;
		Tent1.rotateAngleX = (float) (drag * speed);
		Tent2.rotateAngleX = (float) (drag * speed);
		Tent3.rotateAngleX = (float) (drag * speed);
		Tent4.rotateAngleX = (float) (drag * speed);
		Tent5.rotateAngleX = (float) (drag * speed);
		Tent6.rotateAngleX = (float) (drag * speed);
		Tent7.rotateAngleX = (float) (drag * speed);
		Tent8.rotateAngleX = (float) (drag * speed);

	}

}
